### ISSUE TITLE
Using "use ..." statements in TCA/Overrides isn't safe

### ISSUE THREAD

**Issue by josefglatz** [Treedent/rt_pages_tree_icons#2]
Prevent using use statements when PHP files get cached

**Comment by josefglatz** [comment]
Sorry I mean "safe" instead of "save" :-]

**Comment by Treedent** [comment]
Hi joush, in wich way using use statement is not safe with cached pages ?

**Comment by josefglatz** [comment]
It's no good idea in files, which get's merged together into one file by the TYPO3 caching framework/system. Those files are for example `ext:yourextension/Configuration/TCA/*.php`. There could be multiple files, which uses the same php `use` statement for a specific namespace.

Several people of the TYPO3 core team told me that not to do ;-)

Using `use` should also be not done in ext:yourext/ext_tables.php (as far as I can remember)

https://docs.typo3.org/typo3cms/TCAReference/ExtendingTca/StoringChanges/Index.html
https://blog.plan2.net/2016/05/11/tca-konfiguration-und-der-typo3-cache/ (in german)

**Comment by Treedent** [comment]
Modification concerning usage of use statement have been commited. Thanks joush.
