### ISSUE TITLE
Fatal error: Cannot use GeneralUtility because the name is already in use

### ISSUE THREAD

**Issue by msollmann** [Treedent/rt_pages_tree_icons#8]
Because of 
```
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Core\Imaging\IconRegistry;
use TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider;
```
in ext_localconf.php the system (TYPO3 9.5 / PHP 7.4) crashes with the following messages (one for every class):

Fatal error: Cannot use TYPO3\CMS\Core\Imaging\GeneralUtility as GeneralUtility because the name is already in use in /typo3temp/var/cache/code/cache_core/ext_localconf_d669dc95e14f77176a9039241aa51d7ff24708da.php on line 2918
Fatal error: Cannot use ...

If I comment the these lines out and use the full class path it works.

**Comment by Treedent** [comment]
It's done with Version 4.1.2 for TYPO3 V10LTS.
